# Update existing tables
spring.jpa.hibernate.ddl-auto=update

# Database configuration for Postgres
spring.datasource.url=jdbc:postgresql://db_postgres:5432/url
spring.datasource.username=jules
spring.datasource.password=julespw
spring.datasource.driver-class-name=org.postgresql.Driver
